# Generated by Django 3.1.2 on 2022-06-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='text',
        ),
    ]
