# Generated by Django 3.1.2 on 2022-06-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20220624_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='price',
        ),
    ]
