# Generated by Django 3.1.2 on 2022-06-29 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20220624_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.CharField(default=datetime.datetime(2022, 6, 29, 13, 24, 14, 211552, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
